- target: a cat
  positive: a cat
  unconditional: a cat
  neutral: a cat
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: a cat closed eyes
  positive: a cat closed eyes
  unconditional: a cat closed eyes
  neutral: a cat closed eyes
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: a dog
  positive: a dog
  unconditional: a dog
  neutral: a dog
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: a dog with closed eyes
  positive: a dog with closed eyes
  unconditional: a dog with closed eyes
  neutral: a dog with closed eyes
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: a tiger
  positive: a tiger
  unconditional: a tiger
  neutral: a tiger
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: a tiger closed eyes
  positive: a tiger closed eyes
  unconditional: a tiger closed eyes
  neutral: a tiger closed eyes
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1