- target: male white person
  positive: male white person
  unconditional: male white person
  neutral: male white person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: male black person
  positive: male black person
  unconditional: male black person
  neutral: male black person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: male indian person
  positive: male indian person
  unconditional: male indian person
  neutral: male indian person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: male asian person
  positive: male asian person
  unconditional: male asian person
  neutral: male asian person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: male hispanic person
  positive: male hispanic person
  unconditional: male hispanic person
  neutral: male hispanic person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: female white person
  positive: female white person
  unconditional: female white person
  neutral: female white person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: female black person
  positive: female black person
  unconditional: female black person
  neutral: female black person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: female indian person
  positive: female indian person
  unconditional: female indian person
  neutral: female indian person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: female asian person
  positive: female asian person
  unconditional: female asian person
  neutral: female asian person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
- target: female hispanic person
  positive: female hispanic person
  unconditional: female hispanic person
  neutral: female hispanic person
  guidance: 4
  rank: 4
  action: enhance
  resolution: 512
  dynamic_resolution: false
  batch_size: 1
