device: 1
pretrained_model_name_or_path: "/home/haoguang/model/black-forest-labs/FLUX.1-dev"

python_name: train_image_real

datasets_folder: datasets
datasets:
  - real_person

image_ids:
  - 610
  - 1743

source_folder: source
target_folder: target

config_name: base

start_step: 0
end_step: 27
num_inference_steps: 28
guidance_scale: 3.5

cfg_eta: 4
noise_scales: 
  - 1

train_iteration: 2
# train_iteration: 1
save_per_steps: 200
train_start: 1
train_count: 1
train_method: full
output_folder: "output/models/image/"

# 生成部分
semantic_lora_path: "output/models/pretrained/elf.pt"
semantic_cfg_scale: 0.75

use_trained_lora_path: 0 # 是否使用已经训练好的lora
trained_lora_path: ""

use_prompts_file: 0 # 1 使用prompts_file_gen来生成图片; 0 不使用prompts_file_gen, 使用prompt
prompts_file: 
  - prompts-person.yaml

use_random_seed: 0 # 1 使用随机seed生成图片; 0 不使用随机seed,使用start_seed_gen顺序生成

output_folder_gen: "output/eval/image/"

prompt: 
  - image of a person

skips: 
  - 10
start_seed_gen: 6000

# scales: 0,0.8,1,1.2,1.5,2
scales: 0,0.8,1.0,1.2,1.5
# scales: 0,0.3,0.5,0.7
count_gen: 20